version: '3.8'

services:
  # CPU-only variant for general compatibility
  demucs-cpu:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=""  # Force CPU mode
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
    volumes:
      - ./temp:/app/temp  # Temporary file storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    mem_limit: 8g
    cpus: 4.0
    profiles:
      - cpu

  # GPU-enabled variant for NVIDIA GPUs
  demucs-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "8001:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
    volumes:
      - ./temp:/app/temp  # Temporary file storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    mem_limit: 12g
    profiles:
      - gpu

  # Development variant with code mounting
  demucs-dev:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "8002:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
      - CUDA_VISIBLE_DEVICES=""  # CPU for development
    volumes:
      - ./app:/app:ro  # Mount source code for development
      - ./temp:/app/temp
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev

volumes:
  temp:
    driver: local